config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'welcome#index'

  resources :tenants, except: [:show]
  resources :receipts, except: [:delete, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
    # before_commit :authenticate_user!

end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :tenant

  validates :date, :period, :tenant, presence: true
end

app/models/tenant.rb
class Tenant < ApplicationRecord
  belongs_to :user
  has_many :receipts

  # scope :user, -> { where(user: current_user.id) }
  validates :name, :address, :rent, :charges, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tenants, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, :address, presence: true

  # scope :tenants -> () { where(user: current_user) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address])
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  def index
    @receipts = Receipt.order('tenant_id', 'date')
    @tenants = current_user.tenants
  end

  def show
    @receipt = Receipt.find(params[:id])
    @current_user = current_user
    respond_to do |format|
      format.html
      format.pdf do
        pdf = ReceiptPdf.new(@receipt, @current_user)
        send_data pdf.render, filename: "quittance_#{@receipt.id}.pdf", type: 'application/pdf', disposition: 'inline'
      end
    end
  end

  def new
    @receipt = Receipt.new
    @tenants = current_user.tenants
  end

  def create
    @receipt = Receipt.new(receipt_params)
    if @receipt.save
      redirect_to receipt_path(@receipt.id)
    else
      render :new
      raise
    end
  end

  private
    def receipt_params
      params.require(:receipt).permit(:period, :date, :tenant_id)
    end

end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def index
    @tenants = current_user.tenants
  end

  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    @tenant.user_id = current_user.id
    if @tenant.save
      redirect_to tenants_path
    else
      render :new
    end
  end

  def edit
    @tenant = Tenant.find(params[:id])
  end

  def update
    @tenant = Tenant.find(params[:id])
    if @tenant.update(tenant_params)
      redirect_to tenants_path
    else
      render :edit
    end
  end

  def destroy
    @tenant = Tenant.find(params[:id])
    if @tenant.destroy
      redirect_to tenants_path
    else
      render :delete
    end
  end

  private
    def tenant_params
      params.require(:tenant).permit(:name, :address, :rent, :charges)
    end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # @name = @current_user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quittance - Gérer vos locataires et vos quittances de loyer</title>
    <meta name="description" content="Gérer vos locataire et générer vos quittances de loyer chaque mois facilement.">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="Quittance - Gérer vos locataires et vos quittances de loyer" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="favicon.ico" />
    <meta property="og:description" content="Gérer vos locataire et générer vos quittances de loyer chaque mois facilement." />
    <meta property="og:site_name" content="Quittance - Gérer vos locataires et vos quittances de loyer" />
  </head>

  <body topmargin="0" leftmargin="0" rightmargin="0" class="bg-gray">
    <%= render 'shared/navbar' %>
    <div class= "container global-card">
      <%= yield %>
    </div>
  </body>
</html>

app/views/receipts/index.html.erb
<div>
  <div class="text-center max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:pt-8 pb-4 lg:px-8 lg:items-center lg:justify-between">
    <h1 class="title">Vos quittances</h1>
  </div>

  <div class="max-w px-4 py-4 mx-auto">
      <% @tenants.each do |tenant| %>
        <div class="flex flex-col justify-center mx-2 my-4 px-6 py-6 bg-white border border-gray-50 shadow rounded">
          <p class="text-md"><%= tenant.name %></p>
          <p><%= tenant.address %></p>
          <% if tenant.receipt_ids.any? %>
            <div class="sm:grid sm:grid-flow-row sm:gap-4 md:grid-cols-3 mt-6">
              <% tenant.receipts.each do |receipt| %>
                <div class="flex flex-col justify-center mx-2 px-6 py-6 bg-white border border-gray-50 shadow rounded">
                  <p class="text-pink text-md"><%= I18n.l(receipt.period, format: "%B %Y", locale: :fr).upcase %></p>
                  <%= link_to receipt_path(receipt, format: "pdf"), target: :blank do %>
                    <i class="fas fa-download"> Télécharger</i>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% else %>
            <%= "Pas de quittance de loyer" %>
          <% end %>
        </div>
      <% end %>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="max-w-7xl mx-auto mt-5 md:mt-0 border-gray md:col-span-2">
  <div class="text-center items-center mb-6 bg-white dark:bg-gray-900">
    <h1 class="title">Nouvelle quittance de loyer</h1>
  </div>

  <div class="form">
    <div class="m-4 bg-white sm:p-6">
      <%= simple_form_for [@receipt] do |f| %>
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6">
            <label for="period" class="label">Période</label>
              <%= f.input :period, label: false, placeholder: "Période", discard_day: true, locale: :fr, input_html: { class: "input-period" } %>
          </div>
          <div class="col-span-6">
            <label for="date" class="label">Date du paiement</label>
              <%= f.input :date, label: false, placeholder: "Date du paiement",  as: :date, html5: true, locale: :fr, input_html: { class: "input" } %>
          </div>
          <div class="col-span-6">
            <label for="tenant" class="label">Locataire</label>
              <%= f.association :tenant, label: false, placeholder: "Locataire", collection: current_user.tenants, :label_method => lambda { |tenant| "#{tenant.name} - #{tenant.address}" } , value_method: :id, input_html: { class: "input" } %>
              <%= link_to "Ajouter un locataire", new_tenant_path, class: "text-blue-400 text-sm" %>
          </div>
      </div>
    </div>
  </div>
  <div class="text-center pb-8 px-4 sm:px-4 mt-6 lg:pb-8 lg:px-8 lg:items-center">
    <div class="inline-flex rounded-md shadow">
      <%= f.submit "Créer une quittance", class: "btn-1"%>
    </div>
  </div>
  <% end %>
</div>

app/views/receipts/show.html.erb
<div>
  <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:pt-8 pb-4 lg:px-8 lg:items-center lg:justify-between">
    <h1 class="title">Quittance de loyer</h1>
  </div>
  <div class="text-center max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:pt-8 pb-4 lg:px-8x lg:items-center lg:justify-between">
    <%= link_to "Télécharger", receipt_path(@receipt, format: "pdf"), target: :blank, class: "btn-1" %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="dropdown">
    <button class="dropbtn" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-bars"></i></button>
      <div class="dropdown-content">
          <p><%= link_to 'Accueil', root_path %></p>
          <p><%= link_to 'Mon compte', edit_user_registration_path %></p>
          <p><%= link_to 'Gérer mes locataires', tenants_path %></p>
          <p><%= link_to 'Historique des quittances', receipts_path %></p>
          <p><%= link_to 'Générer une quittance', new_receipt_path %></p>
          <p><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %></p>
      </div>
    </div>
</div>

app/views/tenants/edit.html.erb
<div class="max-w-7xl mx-auto mt-5 md:mt-0 border-gray md:col-span-2">
  <div class="text-center items-center mb-6 bg-white dark:bg-gray-900">
    <h1 class="title">Editer un locataire - <%= @tenant.name %></h1>
  </div>
  <div class="form">
    <div class="m-4 bg-white sm:p-6">
      <%= simple_form_for [@tenant] do |f| %>
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6">
            <label for="name" class="label">Prénom et nom</label>
              <%= f.input :name, label: false, autocomplete: :name, placeholder: "Nom", input_html: { class: "input" } %>
          </div>
          <div class="col-span-6">
            <label for="address" class="label">Adresse</label>
              <%= f.input :address, label: false, as: :search, autocomplete: :address, id: "tenant_address", input_html: { class: "input" } %>
          </div>
          <div class="col-span-3">
            <label for="rent" class="label">Loyer (&euro;)</label>
              <%= f.input :rent, label: false, as: :integer, wrapper: false, hint: false, placeholder: "Loyer", input_html: { class: "input" } %>
          </div>
          <div class="col-span-3">
            <label for="charges" class="label">Charges (&euro;)</label>
              <%= f.input :charges, label: false, as: :integer, placeholder: "Charges", input_html: { class: "input" } %>
          </div>
        </div>
    </div>
  </div>
    <div class="text-center pb-8 px-4 sm:px-4 mt-6 lg:pb-8 lg:px-8 lg:items-center">
      <div class="inline-flex rounded-md shadow">
        <%= f.submit "Ajouter un.e locataire", class: "btn-1" %>
      </div>
    </div>
<% end %>
</div>

app/views/tenants/index.html.erb
<div >
  <div class="text-center max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:pt-8 pb-4 lg:px-8 lg:items-center lg:justify-between">
    <h1 class="title">Mes locataires</h1>
  </div>

    <div class="max-w px-4 py-4 mx-auto">
      <div class="sm:grid sm:grid-flow-row sm:gap-4 sm:grid-cols-3">
        <% @tenants.each do |tenant| %>
        <div class="flex flex-col justify-center mx-2 px-6 py-6 bg-white border border-gray-50 shadow rounded">
          <div>
            <div class="flex items-center justify-end gray text-md">
              <%= link_to edit_tenant_path(tenant.id) do %>
                <i class="fas fa-pen"></i>
              <% end %>
            </div>
            <p class="text-md"><%= tenant.name%></p>
            <p><%= tenant.address %></p>
            <p><%= "A payer : #{tenant.rent + tenant.charges}€" %></p>
          </div>
        </div>
  <% end %>

      </div>
    </div>

  <div class="py-6 text-center">

    <div class="inline-flex rounded-md shadow">
      <%= link_to "Créer un nouveau locataire", new_tenant_path, class: "btn-1" %>
    </div>
    <div class="lg:ml-3 md:ml-3 inline-flex rounded-md shadow">
      <%= link_to "Créer une quittance", new_receipt_path, class: "btn-2" %>
    </div>
  </div>
</div>

app/views/tenants/new.html.erb
<div class="max-w-7xl mx-auto mt-5 md:mt-0 border-gray md:col-span-2">
  <div class="text-center items-center mb-6 bg-white dark:bg-gray-900">
    <h1 class="title">Nouveau locataire</h1>
  </div>
  <div class="form">
    <div class="m-4 bg-white sm:p-6">
      <%= simple_form_for [@tenant] do |f| %>
        <div class="grid grid-cols-6 gap-6">
          <div class="col-span-6">
            <label for="name" class="label">Prénom et nom</label>
              <%= f.input :name, label: false, autocomplete: :name, placeholder: "Nom", input_html: { class: "input" } %>
          </div>
          <div class="col-span-6">
            <label for="address" class="label">Adresse</label>
              <%= f.input :address, label: false, as: :search, placeholder: "Adresse", id: "tenant_address", input_html: { class: "input" } %>
          </div>
          <div class="col-span-3">
            <label for="rent" class="label">Loyer (&euro;)</label>
              <%= f.input :rent, label: false, as: :integer, wrapper: false, hint: false, placeholder: "Loyer", input_html: { class: "input" } %>
          </div>
          <div class="col-span-3">
            <label for="charges" class="label">Charges (&euro;)</label>
              <%= f.input :charges, label: false, as: :integer, placeholder: "Charges", input_html: { class: "input" } %>
          </div>
        </div>
    </div>
  </div>
    <div class="text-center pb-8 px-4 sm:px-4 mt-6 lg:pb-8 lg:px-8 lg:items-center">
      <div class="inline-flex rounded-md shadow">
        <%= f.submit "Ajouter un.e locataire", class: "btn-1" %>
      </div>
    </div>
<% end %>
</div>

app/views/welcome/index.html.erb
<div>
  <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:pt-8 pb-4 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h1 class="title">Bonjour <%= current_user.name%>,</h1>
  </div>
  <div class="max-w-7xl mx-auto py-8 px-4 sm:px-6 lg:py-16 lg:px-8 lg:flex lg:items-center lg:justify-between">
    <h2 class="text-3xl tracking-tight text-gray-900 sm:text-4xl">
      <span class="block text-gray-600">Voulez-vous générer une nouvelle quittance de loyer ?</span>
      <span class="block text-blue-400">Ou ajouter un nouveau locataire ?</span>
    </h2>
  </div>
    <div class="text-center max-w-7xl mx-auto pb-8 px-4 sm:px-4 lg:pb-8 lg:px-8 lg:items-center">
      <div class="inline-flex rounded-md shadow">
        <%= link_to "Nouvelle quittance", new_receipt_path, class: "btn-1" %>
      </div>
      <div class="lg:ml-3 md:ml-3 inline-flex rounded-md shadow">
          <%= link_to "Nouveau locataire", new_tenant_path, class: "btn-2"  %>
      </div>
    </div>
</div>